name: example
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}"
          sleep 300
